### ISSUE TITLE
kan plugin niet installeren

### ISSUE THREAD

**Issue by fabermichiel** [rduivenvoorde/pdokservicesplugin#10]
In de dev-versie van QGIS krijg ik een foutmelding bij het instaleren van de pdok plugin:
type object 'QgsApplication' has no attribute 'qgisUserDbFilePath'.

Wat gaat er mis en wat kan ik doen om het op te lossen?
QGIS versie:
2.99.0-Master / 1182816 / QGIS-OSGeo4W-2.99.0-9-Setup-x86_64.exe	van 27-Feb-2017 05:47
Windows:
Windows 7 Pro SP1 64 bit

**Comment by rduivenvoorde** [comment]
This was because the api was still changing. Fixed, and newer version should work.
Closing as fixed
