### ISSUE TITLE
Crash na openen kaartlaag via PDOK services

### ISSUE THREAD

**Issue by bramvv89** [rduivenvoorde/pdokservicesplugin#106]
QGIS crasht na het openen van een kaartlaag via PDOK plug-in. Enig idee waardoor dit kan komen?
![QGIS crash](https://github.com/rduivenvoorde/pdokservicesplugin/assets/137874041/27e2bb5f-9115-4a13-b956-42bc9a094d2e)

**Comment by rduivenvoorde** [comment]
Hi Bram,
Kun je wat meer context geven:
- welke QGIS, wel Operating Systeem
- wat deed je precies? Hij opent zo te zien wel de dialoog, en dan ga je zoeken naar iets in de lagenlijst?
