### ISSUE TITLE
Markering adreszoeker

### ISSUE THREAD

**Issue by Wietze1991** [rduivenvoorde/pdokservicesplugin#107]
Een tijd geleden is de adresmarkering van de PDOK plug-in gewijzigd. Er kwam altijd een kruisje op de kaart bij het adres dat was ingevoerd. Dit kruisje bleef staan zolang het adres in de adreszoeker stond. In de huidige versie is het een puntje/lijntje welke knippert en na een aantal seconden verdwijnt. Zou deze instelling weer terug gedraaid kunnen worden.

**Comment by rduivenvoorde** [comment]
Hi Wietze, probeer een de nieuwe versie (0.4.2). Ik heb het gele kruisje weer tevoorschijn getoverd! \o/

**Comment by Wietze1991** [comment]
Top! Dankjewel!

 
Met vriendelijke groet,
 
Wietze 
Weening
Adviseur Hydrologie
 
 
Pyrietstraat 1
1812 SC Alkmaar
 
Telefoon: 
072 5064817 | 
0683428746
E-Mail:
***@***.***
Website:
tjadenadvies.nl
 
 
Op dit e-mailbericht en bijbehorende bijlagen zijn de algemene voorwaarden van Tjaden Adviesbureau voor Grondmechanica BV van toepassing.
Van: Richard Duivenvoorde ***@***.***>
Verzonden: vrijdag 22 december 2023 12:38
Aan: rduivenvoorde/pdokservicesplugin ***@***.***>
CC: Wietze Weening | Tjaden Advies ***@***.***>; Author ***@***.***>
Onderwerp: Re: [rduivenvoorde/pdokservicesplugin] Markering adreszoeker (Issue #107)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Hi Wietze, probeer een de nieuwe versie (0.4.2). Ik heb het gele kruisje weer tevoorschijn getoverd! \o/

-
