### ISSUE TITLE
Installing plugin through GUI with: "Error reading metadata: general"

### ISSUE THREAD

**Issue by MartijnVerkleij** [rduivenvoorde/pdokservicesplugin#11]
When attempting to install this plugin, it failed with the error message:

`Error reading metadata: general`

I found out that the error was referring to the metadata.txt file required in a QGIS plugin. Upon inspection I found out that the author and email fields are in the metadata file twice, and I think that this causes the error. When I commented out the offending occurences, the plugin started working again.

**Comment by MartijnVerkleij** [comment]
I just found out that this error is already fixed in this repository, but the version on the QGIS repositories is still using the older metadata.txt that triggers this error.

**Comment by rduivenvoorde** [comment]
Hi Martijn,
thanks for noting, and sorry for not replying earlier. I do not receive the issue emails of github :-(
closing this one, as fixed earliers
Regards,
Richard
