### ISSUE TITLE
PDOK werkt niet meer sinds december 2023

### ISSUE THREAD

**Issue by RichardGerritsen** [rduivenvoorde/pdokservicesplugin#110]
Nadat bleek dat versie 3.28 verschillende Pdok kaarten niet meer ondersteund net de nieuwe 3.34 versie geinstalleerd, maar de kaarten werken nog niet. Ook de Pdok plugins verwijderd en opnieuw geinstalleerd, maar niets helpt. Sommige kaarten zoals  'bouwvlak' werken nog wel, maar kaarten als luchtfoto en N2000 en vele anderen,  geven in het linker overzicht een rood driehoekje. Mogelijk iets met coordinaten? Of doe ik wat anders verkeerd?

Mvg,
Richard

**Comment by rduivenvoorde** [comment]
Hoi Richard,

Dit is niet een issue met de Plugin, of met QGIS verwacht ik. 
Maar PDOK verandert nog wel eens de url's van kaartlagen, of verwijdert zelfs sommige services/kaartlagen.
Eigenlijk is de plugin gewoon een lijst met mogelijk service-url's die bij gebruik in je QGIS project worden opgeslagen.
Wanneer echter PDOK die service-url verandert, OF als ze de hele service zelfs niet meer gebruiken, dan blijft QGIS (door die oude url in het projectbestand) een niet meer geldige service url aanroepen.
Er zit niets anders op, dan te kijken of je (met de nieuwste versie van de pdok plugin), de laag (op naam) weer kunt vinden, en dan weer in je project laden en opslaan.

OF begrijp ik je verkeer? 
Heb je evt wat namen of url's die fout gaan?

**Comment by emacgillavry** [comment]
Heren,

Zie de info op
https://geoforum.nl/t/verstoring-meerdere-pdok-services-en-diensten/9000

Mag,

Edward

Op di 5 dec 2023 21:58 schreef Richard Duivenvoorde <
***@***.***>:

**Comment by RichardGerritsen** [comment]
Bedankt heren,

Het blijkt idd wss dan een kpn probleempje te zijn geweest. Alles lijkt het weer te doen. Gelukkig maar!

mvg,

Richard
