### ISSUE TITLE
WM(T)S layers don't work anymore in QGIS 3.28 LTR

### ISSUE THREAD

**Issue by Vincentvd-T** [rduivenvoorde/pdokservicesplugin#121]
Internally we use QGIS 3.28.5-Firenze. Since the last update of the plugin, added WM(T)S layers are not visible anymore. The layers are added but they don't appear in the map.
* WMTS layers: adding these from the plugin show a question mark next to the added layer, indicating the CRS is unknown. Manually setting this in the layer properties does not solve the problem. 
* WMS layers: The question mark is not visible but the map is still not loading.

Manually adding the layers from PDOK does work.

Below the connection information of 2 faulty layers.

```
Name	OpenBasisKaart - OSM - EPSG:28992
URL	https://www.openbasiskaart.nl//mapcache/wmts/?SERVICE=WMTS&REQUEST=GETCAPABILITIES
Source	tileMatrixSet=rd&layers=osm&styles=default&format=image/png&url=https://www.openbasiskaart.nl//mapcache/wmts/?SERVICE%3DWMTS%26REQUEST%3DGETCAPABILITIES
Provider	wms
```
```
Name	TOP1000raster [TOP1000raster]
URL	https://service.pdok.nl/brt/topraster/wms/v1_0?request=GetCapabilities
Source	crs=EPSG:28992&layers=top1000raster&styles=default&format=image/png&url=https://service.pdok.nl/brt/topraster/wms/v1_0?request=GetCapabilities&service=WMS
Provider	wms
```

System information:
* Windows 10
* pdokservicesplugin 5.1.0

**Comment by rduivenvoorde** [comment]
Hi Vincent, da's vervelend. Ik dit probleem hier bij mijn zelf niet reproduceren. Maar had ook geen 3.28 meer, ben die nu aan het compileren...

Wat zijn jou standaardinstellingen voor een nieuw project? Als je een blanco project aanmaakt: is het dan EPSG:28992 of EPSG:4326 of EPSG:3857 ?

En het moment dat je een wms of wmts toe wilt voegen, start je dan uit een bestaand project? Of met een blanco project?
Wil je evt beide even proberen en terugrapporteren?

Kun jij evt kijken of het bij jou (onder Windows10) ook optreedt bij een nieuwere QGIS 3.34 is de huidige LTR versie, of nog nieuwer, de net vrijgekomen 3.36? Ga ik intussen verder proberen 3.28 aan de praat te krijgen.

Graag wat meer info, om te kijken of ik het kan reproduceren.
Dat rode kruisje krijg je idd als je niet een crs aangeeft of het crs niet beschikbaar is, anyway een crs issue

Je kunt (na F12 te hebben gebruikt) de url's zien die QGIS de deur uitstuurt. Kun je daar eens een of 2 van rapporteren?

**Comment by Vincentvd-T** [comment]
Hey @rduivenvoorde ,

Dank voor de snelle reactie, hier de gevraagde informatie:
* Standaard start QGIS in EPSG4326. Ik heb verder geen aanpassingen gemaakt aan het standaardproject.
* Ik voeg het vanuit een blanco project toe maar ook in een bestaand project doet het probleem zich voor.
* Ik heb een log toegevoegd. De eerste 4 verzoeken zijn van de WMTS en WMS. De laatste zijn van een WFS ter vergelijking wat wel werkt.
* Ik kan helaas niet op korte termijn proberen of het wel in de nieuwste versie werkt. Als je het in 3.28 niet gereproduceerd krijgt dan zal ik het sowieso testen.
* Ik heb ook het cache eens verwijderd maar dat help niet (zo ook wel vreemd zijn als ineens meerdere gebruikers binnen onze organisatie tegelijk cache problemen krijgen).

**LOG**
[pdok_plugin_log.json](https://github.com/user-attachments/files/16311211/pdok_plugin_log.json)

**Comment by rduivenvoorde** [comment]
@Vincentvd-T ik kan het reproduceren in 3.28 :-(  

Zal even kijken of ik t kan fixen

**Comment by rduivenvoorde** [comment]
@Vincentvd-T ik denk dat ik die wmts kan fixen, de crs is uit de wmts-uri gevallen.

Maar jouw WMS lijkt bij mij tenminste ook te werken. Ook als ik 3.28 en plugin versie 5.1.0 gebruik..
Wat me wel opvalt: als je een andere crs gebruikt dan 28992, dan zoomt QGIS naar een te groot gebied in, en daar geeft de service een wit vlak... Als je dan inzoomt, of op basis van een provinciekaart erheen zoomt, dan werkt die wel.

Of heb je nog andere WMS'en die niet werkten?

**Comment by Vincentvd-T** [comment]
> @Vincentvd-T ik denk dat ik die wmts kan fixen, de crs is uit de wmts-uri gevallen.

Ah, top


> Maar jouw WMS lijkt bij mij tenminste ook te werken. Ook als ik 3.28 en plugin versie 5.1.0 gebruik..
> Wat me wel opvalt: als je een andere crs gebruikt dan 28992, dan zoomt QGIS naar een te groot gebied in, en daar geeft de service een wit vlak... Als je dan inzoomt, of op basis van een provinciekaart erheen zoomt, dan werkt die wel.

Ik denk dat ik gewoon de verkeerde WMS heb gepakt om te proberen, mijn fout. Bij die top1000 moet je niet te ver zijn uit- of ingezoomd zijn. Ik had het met de provincies geprobeerd maar was daarbij kennelijk nog te ver uitgezoomd. WMS'en werken dus gewoon.

**Comment by rduivenvoorde** [comment]
Ok, er staat straks een 5.1.1 klaar. Die zou dit issue niet meer moeten hebben.

**Comment by vincentvd1** [comment]
@rduivenvoorde Dank voor de snelle actie. Ik kan bevestigen dat het weer werkt in v3.28

**Comment by rduivenvoorde** [comment]
Dank voor het melden!
