### ISSUE TITLE
Basisregistratie Grootschalige Topografie Stylen in de OGC laag zijn niet allemaal zichtbaar

### ISSUE THREAD

**Issue by KayArne** [rduivenvoorde/pdokservicesplugin#122]
Bij het laden van deze lagen zijn niet alle styles meer zichtbaar in qgis

![image](https://github.com/user-attachments/assets/d3c54662-9521-4f13-9395-332669db09f8)
![image](https://github.com/user-attachments/assets/e79a91a4-5858-4ae2-9560-c5f722df0cca)

Waarschijnlijk doe ik iets verkeerd..

**Comment by rduivenvoorde** [comment]
Hoi Arne,

De stylen lijken er wel te zijn (zie screendumpje).
Maar QGIS lijkt het niet zo te renderen/kleuren als op jouw screenshot.

![image](https://github.com/user-attachments/assets/017dcba2-857a-4102-974f-663889c2c6ec)

Ik heb de vraag ook even op Geoforum gegooid:
https://geoforum.nl/t/bgt-vector-tiles-en-styles-in-qgis/9785

Ikzelf heb dit nooit gebruikt of gecontroleerd eerlijk gezegd.

**Comment by KayArne** [comment]
Ik zag de reactie bij het Geoforum. Wachten we hun conclusie wel af!
Dank voor de moeite!

**Comment by KayArne** [comment]
Helemaal super, dankjewel voor de moeite!

**Comment by rduivenvoorde** [comment]
![Screenshot from 2024-08-19 15-15-02](https://github.com/user-attachments/assets/86568baa-5f12-45ab-9312-a3faa5311503)

Ok doet het dus weer. 

Er was dus iets mis met de tiles, niet met QGIS of de plugin.

Dan sluit ik deze hier.
