### ISSUE TITLE
Kon plug-in 'pdokservicesplugin' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

### ISSUE THREAD

**Issue by pphjed** [rduivenvoorde/pdokservicesplugin#13]
Melding: Kon plug-in 'pdokservicesplugin' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

Plugin laadt niet, onderstaande meldingen worden weergegeven.

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS 3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pdokservicesplugin/__init__.py", line 27, in classFactory
    from .pdokservicesplugin import PdokServicesPlugin
  File "/Applications/QGIS 3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pdokservicesplugin/pdokservicesplugin.py", line 34, in 
    from future import standard_library
  File "/Applications/QGIS 3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'

Python versie: 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS versie: 3.0.0-Girona Girona, exported 

Python pad:
/Applications/QGIS 3.app/Contents/MacOS/../Resources/python
/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS 3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/GEOS.framework/Versions/3B/Python/3.6/site-packages
/Library/Frameworks/GDAL.framework/Versions/2.2/Python/3.6/site-packages
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview
/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res

**Comment by evetion** [comment]
`pip install future` lost dit probleem op, als je dat in de Python omgeving die wordt gebruikt door QGIS doet.
