### ISSUE TITLE
Feature request: support selection of source projection

### ISSUE THREAD

**Issue by anneb** [rduivenvoorde/pdokservicesplugin#16]
Many (most?) PDOK services now support multiple projections. Besides EPSG:28992, now most services also support EPSG:3857. When using tiled WMTS services, the tiles projected in EPSG:28992 do not look nice when reprojected and displayed in an EPSG:3857 projection due to different scale levels and raster reprojection artifacts.

if you replace "EPSG:28992" by "EPSG:3857" in file pdokservicesplugin.py, function loadService in the code block under 'elif servicetype=="wmts":', then QGIS correctly loads and displays the EPSG:3857 version of the WMTS tilesets.

I think it would be a very be nice feature if there could be something like a drop down list of supported projections for the selected layer next to the button "Laad deze laag in QGIS (of dubbelklik op de regel)".

**Comment by rduivenvoorde** [comment]
Hi @anneb, mmm I want to keep the dialog as simple as possible. Users of the plugin (I think) are not very aware of the different crs's. Letting them choose between different crs's via dropdowns or radio's seems to make things more complicated?
I could though... during the building of the (now giant) pdok.json file for the WMTS-service check if there is a second crs, and add a line for those in the layer list. A WMTS layer will then be 2 times in that list:
"Luchtfoto 2017 Ortho 25cm RGB (epsg:28992)"
and
"Luchtfoto 2017 Ortho 25cm RGB (epsg:3857)"

I do the same for WMS layers if they are availabe in different styles.

Off course it is also easy to just grab the capabilities url and define a service yourself? (but also mostly for 'advanced' users).
Another idea is to extent the little toolbar we have now with two 'buttons' being your 2 favourite layers (thinking that user probably have a favourite topo and lufo layer...)
What you think?

**Comment by anneb** [comment]
I have already started working on the feature.  See image below. I think the user can be helped by selecting either 'EPSG:28992' by default or look at the current project projection and pre-select that projection if available. 

However... I just discovered that pdok.json does not contain all supported projections. The capabilities response often has more projections than the pdok.json. Retrieving capabilities for every selected layer will make the plugin much slower...

![image](https://user-images.githubusercontent.com/839432/39971341-8953cb4a-56f9-11e8-87c6-c6cdaa6f5539.png)

**Comment by rduivenvoorde** [comment]
@anneb well, I was thinking you were talking about the wmTs's only here. And in the pdok2json.py I would check IF they are available.
I think the nice thing about current plugin is that it is so very easy to just pick a layer from one of the >9000 now...  But your proposal could be ok too: we keep the behaviour as is, and load in 28992 as default and upon double clicking. Then the dropdown could (one time?) determine a different crs (we could also make it a setting: 'preferred crs').
Qua implementation: will you then check for every layer IF certain crs's are available? I think we will have: 4326 (all), 28992 (all), 3857 (wmts's?), EPSG:25831:RWS (water/sea related?), ...uh, some have 9:
https://geodata.nationaalgeoregister.nl/inspire/au/ows?SERVICE=WMS&request=getcapabilities 
has
```
<CRS>EPSG:25831</CRS>
<CRS>EPSG:25832</CRS>
<CRS>EPSG:28992</CRS>
<CRS>EPSG:3034</CRS>
<CRS>EPSG:3035</CRS>
<CRS>EPSG:3857</CRS>
<CRS>EPSG:4258</CRS>
<CRS>EPSG:4326</CRS>
<CRS>CRS:84</CRS>
```

I have also been thinking about a really better gui, for example not retrieving all layers in the pdok.json, but more 'lazy' loading: a tree structure with only the services in it, and not earlier then when you open a node/service the layers are retrieved... Hard part is to create a structure like that, and we would miss the search/filter we have now...

**Comment by anneb** [comment]
About the UI: I think the UI is brilliant because it is simple, fast and search works very well. A centralized pdok.json is also much faster and better than risking parsing errors from many clients and versions to many pdok services that may change their capabilities any time.

I have forked this project, https://github.com/Geodan/pdokservicesplugin, then:
* added/fixed reading of all CRS for WMTS and WMS into pdok.json
* added dropdown list for CRS selection
* load all CRSs from the selected layer in into dropdown list, default selection to EPSG:28992
* read selected CRS from dropdown while adding the selected layer to QGIS

I tested this with QGIS on Windows by updating the source files in the plugin directory and reloading QGIS, seems to work fine
I don't know how to test this on Linux. If I just update the .py files and reload Qgis, the plugin loader complains with message: ImportError: cannot import name Qgis. I do not have a full Qgis development environment, could that be the problem?

**Comment by rduivenvoorde** [comment]
@anneb will have a look later, happy to merge a PR then

**Comment by anneb** [comment]
Added PR https://github.com/rduivenvoorde/pdokservicesplugin/pull/17

**Comment by anneb** [comment]
@rduivenvoorde Your updates described in the PR comments for QGIS2.x work well, also on my Ubuntu laptop. New dropdown-button looks nice.

Thanks!

I think this issue can be closed?
