### ISSUE TITLE
Update PDOK data

### ISSUE THREAD

**Issue by NelisV** [rduivenvoorde/pdokservicesplugin#24]
Beste, ik maak graag en veel gebruik van deze plugin in QGIS voor allerlei projectjes. echter lijkt de bron al best een lange tijd niet meer te updaten. de laatste nieuwe data die ik op kan vragen is van 27-01-2019. wordt de source niet meer geupdate? of heeft dit iets te maken met de plugin? als inderdaad de source het probleem is is zal ik contact zoeken met PDOK zelf. 

Dank!

**Comment by rduivenvoorde** [comment]
@NelisV Sorry ik was een beetje druk, en ik moet de url's handmatig aanpassen.... Maar het goede nieuws: er is straks een nieuwe versie: 3.5.0 met daarin een ander icoontje EN allemaal werkende url's.
Groet,
Richard Duivenvoorde
