### ISSUE TITLE
Kadastralekaart v3

### ISSUE THREAD

**Issue by bvdbos** [rduivenvoorde/pdokservicesplugin#25]
Eén van de basisfunctionaliteiten (imho) van PDOK werkt niet meer in de plugin, de kadastrale kaart v3 is vervallen, zie:
https://www.pdok.nl/-/webservices-kadastrale-kaart-v3-niet-meer-actief-per-1-juni-2020

**Comment by rduivenvoorde** [comment]
Zie https://github.com/rduivenvoorde/pdokservicesplugin/pull/26
Ik heb vandaag een nieuwe versie 3.5.0 uitgerold. Alles zou het weer moeten doen (EN een nieuw pdok icoontje...)
Groet,
Richard

**Comment by bvdbos** [comment]
Werkt perfect en al op te waarderen via qgis : 
![afbeelding](https://user-images.githubusercontent.com/1064079/85162609-f0381300-b261-11ea-8dfc-27f465f19599.png)
