### ISSUE TITLE
Kon plug-in 'pdokservicesplugin' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

### ISSUE THREAD

**Issue by bakkerss** [rduivenvoorde/pdokservicesplugin#30]
Hello,

Today I installed a new version of QGIS 3.16.3-Hannover. During the installation of the plugin I receive an error message so I am unable to install the plugin. As it is a very useful plugin it would be great if this issue can be fixed.

Below you can find the details of the error message and the QGIS version details.

UnboundLocalError: local variable 'locale' referenced before assignment 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/sebas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdokservicesplugin\__init__.py", line 28, in classFactory
    return PdokServicesPlugin(iface)
  File "C:/Users/sebas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdokservicesplugin\pdokservicesplugin.py", line 90, in __init__
    localePath = self.plugin_dir + "/i18n/pdokservicesplugin_" + locale + ".qm"
UnboundLocalError: local variable 'locale' referenced before assignment

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python pad:
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python
C:/Users/sebas/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/sebas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/sebas/AppData/Roaming/QGIS/QGIS3\profiles\default/python

QGIS-versie
3.16.3-Hannover
QGIS code revisie
94ac9f21b8
Gecompileerd tegen Qt
5.11.2
Gebruikt nu Qt
5.11.2
Gecompileerd tegen GDAL/OGR
3.1.4
Gebruikt nu GDAL/OGR
3.1.4
Gecompileerd tegen GEOS
3.8.1-CAPI-1.13.3
Gebruikt nu GEOS
3.8.1-CAPI-1.13.3
Gecompileerd tegen SQLite
3.29.0
Uitgevoerd met SQLite
3.29.0
PostgreSQL Client Versie
11.5
SpatiaLite-versie
4.3.0
QWT versie
6.1.3
QScintilla2 Versie
2.10.8
Gecompileerd tegen PROJ
6.3.2
Gebruikt nu PROJ
Rel. 6.3.2, May 1st, 2020
Versie OS
Windows 10 (10.0)
Actieve plug-ins van Python
db_manager; 
MetaSearch; 
processing; 
pdok_locatieserver_locator_filter

**Comment by rduivenvoorde** [comment]
@bakkerss something to do with the translation code, which we do not use anyway. So I threw away all of it in the new 3.6.0... :-)
Closing this one, but plz reopen if you think it isn't fixed.
