### ISSUE TITLE
Generieke locatieserver class implementeren

### ISSUE THREAD

**Issue by arbakker** [rduivenvoorde/pdokservicesplugin#32]
Doel is om meerdere componenten in de nieuwe versie van de plugin onder te brengen:

- [nominatim locator plugin](https://plugins.qgis.org/plugins/nominatim_locator_filter/) 
- [locatieserver processing tool](https://gist.github.com/arbakker/e67268ca18633a48f96ee67898c64f2e/)

De generieke locatieserver class maakt het mogelijk code te delen tussen deze componenten. 

HTTP requests moeten gedaan worden met behulp van [QgsBlockingNetworkRequest](https://qgis.org/api/classQgsBlockingNetworkRequest.html) voor proxy en authenticatie support van QGIS3

**Comment by rduivenvoorde** [comment]
Even wat brainstormen...

het gebruik van de locatieservers in de huidige plugins/code is nogal gevarieerd:
In
https://github.com/rduivenvoorde/pdokservicesplugin/blob/master/pdokgeocoder.py
wordt zowel de suggest, free als de lookup interface gebruikt, terwijl in de locator
https://github.com/rduivenvoorde/pdok_locatieserver_locator_filter/blob/master/pdoklocatieserverfilter.py
gebruikt suggest en lookup
en 
https://github.com/rduivenvoorde/pdok_locatieserver_locator_filter/blob/master/pdoklocatieserverfilter.py
gebruikt free en lookup

De generieke class/module moet dus alle drie kunnen 'bevragen'...
Vraag is dan een beetje: wat 'geven' die zoekfuncties terug?
Geven ze gewoon een soort Dict's terug a la
https://github.com/rduivenvoorde/pdokservicesplugin/blob/master/pdokgeocoder.py#L171-L195
en dus afhankelijk van het (fq) type?
Of moet daar weer een wrappertje omheen?
Of gaan we meteen 'QgsFeatures' aanmaken in deze module? Of houden we 'm juist generiek?

**Comment by arbakker** [comment]
Mijn voorkeur heeft het om de LS class niet teveel te laten doen, dus een dict dan. Mocht het handig zijn kunnen we altijd nog een convenience class toevoegen die QgsFeatures maakt van de LS objecten.

Ik heb [hier](https://github.com/arbakker/pdok-ls-lib) een eerste aanzet gemaakt. Is nogal minimaal, met een hoop cruft aangezien ik een cookiecutter project heb gebruikt. Kostte nogal wat moeite om het dit zonder QGIS te starten aan de praat te krijgen. Hoop geleerd zullen we maar zeggen 😄

**Comment by arbakker** [comment]
Done: https://github.com/rduivenvoorde/pdokservicesplugin/pull/37
