### ISSUE TITLE
JSON config bestand genereren op basis van NGR

### ISSUE THREAD

**Issue by arbakker** [rduivenvoorde/pdokservicesplugin#33]
Genereren JSON config bestand op basis van NGR. Zodat het handmatig updaten van de lijst van services niet meer nodig is. 

- gebruik maken van [owslib](https://geopython.github.io/OWSLib/) voor het parsen van service capabilities
- waarschijnlijk biedt owslib ook ondersteuning voor querien CSW,

**Comment by arbakker** [comment]
@raymondnijssen, @rduivenvoorde  [hier](https://github.com/arbakker/pdok-spider-python) een beginnetje gemaakt voor het generen van de config op basis van NGR records.

**Comment by rduivenvoorde** [comment]
Nice! Hij begint bij mij wel goed, maar kapt af op een error in owslib.

Ik zal er komende dagen zelf even induiken. Misschien in een try/except zetten en dan de errors loggen? Ik weet dat er nogal veel mis kan gaan met de capability documentjes (mixed character encoding, versie probleempjes etc etc ...)

Of zoiezo even kijken of het mogelijk is om 2 outputs te genereren: 1 voor de json en een voor logging ofzo (logging module gebruiken?)?

FYI:

```
(venv) [richard@oost pdok-spider-python (main)]$ ./spider.py -n 1 output.json
2021-04-26 08:23:13,844 - INFO: https://geodata.nationaalgeoregister.nl/inspire/ps-rvo-np/wms?request=GetCapabilities&service=WMS
2021-04-26 08:23:14,074 - ERROR: error occcured processing WMTS service, id: 6d23a02b-5a8a-447e-a481-ddb2a085c1fa, url: https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/WMTSCapabilities.xml?request=GetCapabilities&service=WMTS
Traceback (most recent call last):
  File "/home/richard/git/pdok-spider-python/./spider.py", line 165, in get_wmts_cap
    wmts = WebMapTileService(url)
  File "/home/richard/git/pdok-spider-python/venv/lib/python3.9/site-packages/owslib/wmts.py", line 189, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "/home/richard/git/pdok-spider-python/venv/lib/python3.9/site-packages/owslib/wmts.py", line 240, in _buildMetadata
    gather_layers(caps, None)
  File "/home/richard/git/pdok-spider-python/venv/lib/python3.9/site-packages/owslib/wmts.py", line 231, in gather_layers
    cm = ContentMetadata(
  File "/home/richard/git/pdok-spider-python/venv/lib/python3.9/site-packages/owslib/wmts.py", line 726, in __init__
    ll = [float(s) for s in lc.text.split()]
AttributeError: 'NoneType' object has no attribute 'text'
2021-04-26 08:23:43,991 - INFO: output written to output.json
```

**Comment by rduivenvoorde** [comment]
Mmm, OK sorry mijn fout. Toch maar even in de code gekeken :-)
Die -n1 haalt maar 1 service url op... vandaar dat hij afbreekt.
Ik haal idd zo 30 services binnen nu.
Ik zie dat er nog een 'layers' key in de json zit, dus hij doet het nog niet in de plugin. Maar: erg mooi al! Dank

**Comment by arbakker** [comment]
>  Laten we vooral even overleggen wie hiermee verder gaat, anders zitten we dubbel werkt te doen...

Lijkt me goed. Als je dit verder wilt oppakken dan is dat prima, maar ik vind het ook niet erg om het zelf te doen. 

Wat betreft de foutafhandeling; alleen specfieke Exceptions die ik bij het ontwikkelen ben tegengekomen worden afgevangen. Dus wellicht verstandig om naast specifieke Exceptions ook een generieke try/except in te zetten, om onvoorziene fouten af te vangen.

**Comment by arbakker** [comment]
>  Ik zie dat er nog een 'layers' key in de json zit, dus hij doet het nog niet in de plugin. Maar: erg mooi al! Dank.

Die layers key wordt er op het einde uitgefilterd, door het plat te slaan, zie https://github.com/arbakker/pdok-spider-python/blob/a940cee403e85dcc69d52391819f1bd444e40f88/spider.py#L180. 

Output ziet er zo uit:

```json
{
        "name": "2017_ortho25IR",
        "title": "2017_ortho25IR",
        "tilematrixsets": "EPSG:28992",
        "imgformats": "image/jpeg",
        "servicetitle": "Web Map Tile Service",
        "url": "https://geodata.nationaalgeoregister.nl/tiles/service/wmts?request=GetCapabilities&service=WMTS",
        "type": "wmts"
    },
    {
        "name": "lufolabels",
        "title": "lufolabels",
        "tilematrixsets": "EPSG:28992",
        "imgformats": "image/png",
        "servicetitle": "Web Map Tile Service",
        "url": "https://geodata.nationaalgeoregister.nl/tiles/service/wmts?request=GetCapabilities&service=WMTS",
        "type": "wmts"
    },
    {
        "name": "TN.CableTransportNetwork.CablewayLink",
        "title": "Vervoersnetwerken - kabelbanen",
        "style": "TN.CableTransportNetwork.CablewayLink.Default",
        "crs": "CRS:84,EPSG:4258,EPSG:4326,EPSG:3035,EPSG:3034,EPSG:3857,EPSG:28992,EPSG:25831,EPSG:25832",
        "minscale": "",
        "maxscale": "",
        "imgformats": "image/png,application/atom+xml,application/json;type=utfgrid,application/pdf,application/rss+xml,application/vnd.google-earth.kml+xml,application/vnd.google-earth.kml+xml;mode=networklink,application/vnd.google-earth.kmz,image/geotiff,image/geotiff8,image/gif,image/jpeg,image/png; mode=8bit,image/svg+xml,image/tiff,image/tiff8,image/vnd.jpeg-png,text/html; subtype=openlayers,text/html; subtype=openlayers2,text/html; subtype=openlayers3",
        "url": "https://geodata.nationaalgeoregister.nl/inspire/tn-c/wms?request=GetCapabilities&service=WMS",
        "servicetitle": "Transport Netwerken - Kabelbanen (INSPIRE geharmoniseerd)",
        "type": "wms"
    }
```

**Comment by arbakker** [comment]
Heb ook een github action workflow aangemaakt: https://github.com/arbakker/pdok-spider-python/blob/main/.github/workflows/update-config.yaml

Vooralsnog wordt die alleen handmatig getriggerd, maar kan ook periodiek, of op push.

**Comment by arbakker** [comment]
Done zie https://github.com/rduivenvoorde/pdokservicesplugin/pull/42
