### ISSUE TITLE
Nieuw project aanmaken voor nieuwe versie van pdokservicesplugin

### ISSUE THREAD

**Issue by arbakker** [rduivenvoorde/pdokservicesplugin#34]
Van scratch beginnen voor nieuwe versie van pdokservicesplugin

- nieuwe interface voor nieuwe versie voor
  - zoekveld ls toolbar optioneel maken
  - apart venster voor instellingen
  
Vervolgens oude herbruikbare code stuk voor stuk opschonen en overzetten.

**Comment by arbakker** [comment]
Ha, ik ben [hier](https://github.com/arbakker/qgis-processing-plugin)  begonnen met een nieuw project, het bevat een tweetal processing algoritmes (nog niet geheel functioneel)  die gebruik maken van een generieke locatieserver lib. 

Ik heb unittests toegevoegd voornamelijk voor het testen van de generieke locatieserver lib. Is het een idee dit project op een nieuwe branch in dit repo over te zetten?

**Comment by rduivenvoorde** [comment]
@arbakker @raymondnijssen misschien even een keer samen zitten om de boel in elkaar te schuiven?

**Comment by arbakker** [comment]
min of meer werkende versie is te vinden in de [develop-2](https://github.com/rduivenvoorde/pdokservicesplugin/tree/develop-2) branch
