### ISSUE TITLE
pdokservicesplugin.py - BBOX te krap

### ISSUE THREAD

**Issue by buddiebubba** [rduivenvoorde/pdokservicesplugin#4]
Bij het toevoegen van een WFS komt er een BBOX bij die te krap staat waardoor een deel van de data wegvalt.

"&BBOX=0,300000,300000,600000"
![2015-10-22_11h25_47](https://cloud.githubusercontent.com/assets/13434995/10663019/a1a42086-78b8-11e5-8a93-8942db9a6d0d.png)

**Comment by rduivenvoorde** [comment]
@buddiebubba yep, is intussen aangepast (sorry dat ik niet eerder reageerde, ik krijg de github issue emailtjes blijkbaar niet binnen). Maar volgens mij had je mij ook een emailtje gestuurd (en heb ik toendertijd het aangepast nav daarvan :-) )

**Comment by buddiebubba** [comment]
Correct :)
