### ISSUE TITLE
WFS services Kadaster werken niet meer

### ISSUE THREAD

**Issue by mathijsalkema** [rduivenvoorde/pdokservicesplugin#45]
Beste Richard, 

Sinds de laatste update werken de WFS services van het Kadaster niet meer. 
Er wordt aangegeven dat de databron gerepareerd moet worden:
_Originele bron-URI:  pagingEnabled='true' restrictToRequestBBOX='1' srsname='EPSG:28992' typename='kadastralekaartv4:perceel' url='https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?request%3DGetCapabilities%26service%3DWFS' version='2.0.0'_ 

De bron is nu:
_pagingEnabled='true' restrictToRequestBBOX='1' srsname='EPSG:28992' typename='kadastralekaartv4:perceel' url='https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?request%3DGetCapabilities%26service%3DWFS' version='2.0.0'_

Gr, Mathijs

**Comment by rduivenvoorde** [comment]
Hi Mathijs, dank voor de melding.

Ik zie inderdaad dat bv de laag bebouwing niet werkt. Wij hebben juist voor het eerst nu alle url's uit het nationaal georegister gehaald. Misschien gaat daar iets mis mee.

Ik begrijp even niet wat je bedoelt met "Er wordt aangegeven dat de databron gerepareerd moet worden:' 
Waar wordt dan aangegeven? De twee url's in jouw stukje zijn identiek?

Het probleem is blijkbaar hoe ik om ga met de url die we krijgen van het Nationaal Georegister.

Ik duik er verder even in, maar als workaround voor jou nu: Als je de service url van die service:
`https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?` gebruikt in de normale WFS dialoog, dan werkt de service wel.

**Comment by mathijsalkema** [comment]
Hi Richard, 

Wat ik bedoelde is dat er een uitroeptekentje achter de ingeladen laag komt te staan in je lagenscherm. Wanneer je daar vervolgens op klikt, wordt het scherm 'Databron repareren' geopend. 

Workaround had ik gevonden, maar voelde toch even de plicht als trouwe gebruiker van de plug-in je hierop te wijzen :) 

Groet, Mathijs

**Comment by rduivenvoorde** [comment]
Ok, ik heb het issue gevonden. Het had te maken met het feit dat ik voor de brt en de kadastrale kaart WMTS'en de url moest fixen, maar blijkbaar gaat dat dan juist mis bij de kadastrale kaart wFs...

Er komt een nieuwe versie 3.7.2 straks...

**Comment by rduivenvoorde** [comment]
Oh, en nog iets anders: ik zie wel dat pdok (OF de wfs provider van QGIS??) tegenwoordig zegt:

2021-11-09T18:17:57     CRITICAL    Layer perceel : Download of features for layer kadastralekaartv4:perceel failed or partially failed: WFS exception report (code=InvalidParameterValue text=
              It is not possible to use a 'startindex' higher then 10.000. When you 
              need to scrape the WFS I kindly refer you to the extracts available 
              for this dataset.
              ). You may attempt reloading the layer with F5

Als je blijkbaar een groot gebied (>10000 features) op wilt halen... Wat wel jammer is, het was best handig om van een plaats even zo alle percelen of gebouwen op te halen...

**Comment by rduivenvoorde** [comment]
Ah, het is PDOK die dat zegt:

https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=kadastralekaartv4:bebouwing&STARTINDEX=11000&COUNT=1000&SRSNAME=urn:ogc:def:crs:EPSG::28992&BBOX=103911.39476094619021751,488441.57337842142442241,106290.58905758152832277,492463.74275752349058166,urn:ogc:def:crs:EPSG::28992
