### ISSUE TITLE
Bestuurlijke grenzen 

### ISSUE THREAD

**Issue by mathijsalkema** [rduivenvoorde/pdokservicesplugin#46]
Hoi Richard, 

Per 01-01-2022 zijn de Bestuurlijke Grenzen offline gehaald door PDOK. Zie dit [artikel](https://www.pdok.nl/introductie/-/article/bestuurlijke-grenzen).

Wil je dit meenemen in een nieuwe update? 

Alvast bedankt!

Mathijs Alkema
Kabelnoord

**Comment by rduivenvoorde** [comment]
Hoi Mathijs, 
Yep als ik een dezer dagen even tijd heb zal ik de lijst met layers updaten.
We (@raymondnijssen en ik) zijn ook bezig met een totale omschrijving van de plugin. Maar dat zal ws langer duren.
Ik sluit deze issue nu, bedankt voor de melding.
