### ISSUE TITLE
verbeteren foutafhandeling o.a. lib/http_client

### ISSUE THREAD

**Issue by arbakker** [rduivenvoorde/pdokservicesplugin#53]
Verbeteren foutafhandeling plugin breed. @rduivenvoorde weet jij een goed voorbeeld te vinden voor hoe foutafhandeling netjes te implementeren in een plugin? Een korte zoekactie op het web leverde zo snel niets op. 

Aandachtspunten zijn iig:
- [lib/http_client](https://github.com/rduivenvoorde/pdokservicesplugin/blob/develop-2/pdokservicesplugin/lib/http_client.py)

**Comment by raymondnijssen** [comment]
Bedoel je hoe je in QGIS feedback kunt geven aan de gebruiker?

Als bijvoorbeeld een service niet werkt kun je in de messageBar boven de kaart een melding geven:

iface.messageBar().pushMessage('Hoi', 'Anton', 2, duration=5)

Je kunt ook naar een messageLog schrijven, die moet de gebruiker wel openklappen met het tekstballonnetje rechtsonder:
QgsMessageLog.logMessage('Anton', 'PDOK plugin', level=2)

levels:
0: info
1: warning
2: critical
3: success

De plugin heeft al een self.info(msg) functie trouwens:
https://github.com/rduivenvoorde/pdokservicesplugin/blob/3999f364b898549d8389de52fc8abab2c0f35093/pdokservicesplugin.py#L849
