### ISSUE TITLE
verwijderen qgis <= 1.8 code

### ISSUE THREAD

**Issue by arbakker** [rduivenvoorde/pdokservicesplugin#55]
Verwijderen qgis <= 1.8 code, deze lijkt me niet meer relevant. Mee eens @rduivenvoorde ?

**Comment by arbakker** [comment]
zie o.a. https://github.com/rduivenvoorde/pdokservicesplugin/blob/a927f76644ec9c43e8495634cda99bb7a2aee004/pdokservicesplugin/pdokservicesplugin.py#L119

**Comment by rduivenvoorde** [comment]
Ja hoor tuurlijk :-)
