### ISSUE TITLE
PDOK - bgt

### ISSUE THREAD

**Issue by Arnicon** [rduivenvoorde/pdokservicesplugin#6]
Hoi Richard,

Als ik bij PDOK.nl een BGT-product download krijg ik heel veel bgt-onderdelen.
bijvoorbeeld: bgt_wegdeel.gml en nog 32 andere.
Waarom lukt het me niet om met behulp van je plugin ook deze informatie in te laden?
Kun je dit (eenvoudig) uitleggen of in de plugin maken?

Voorheen gebruikte ik stukken GBKN van het kadaster. Echter wordt deze niet meer bijgewerkt door ontwikkeling van BGT. Maar BGT is nog niet compleet voor Nederland.
Het is nu gewoon zoeken naar de beste topografie!
Omdat ik geregeld aanpassingen moet doen gebruik ik ook autoCAD.
Het moet (goed) vectoriseerbaar zijn. Ik laad diverse lagen in QGIS uit de PDOK-plugin maar heb niet het idee dat er structuur in zit. Er zijn bijvoorbeeld vele lagen voor kadastrale grens.
Waarom zoveel verschillende?

Graag reactie! Alvast Hartelijk bedankt!

**Comment by rduivenvoorde** [comment]
@Arnicon sorry dat ik niet eerder reageerde, maar ik krijg de github emailtjes niet...
Dat BGT en dergelijke zo slecht 'werken' heeft te maken met de complexiteit van de gml ed.
Probeer anders eens de 'bgt downloader plugin', en intussen is ook GDAL aangepast om beter om te kunnen gaan met het soort 'complexe' GML wat pdok soms serveert.
Daarnaast komt er voor QGIS3 een plugin uit die hier nog beter mee om moet kunnen gaan.

Voor nu sluit ik deze even.

**Comment by Arnicon** [comment]
Sorry, te druk geweest met andere zaken.
Hopelijk vind ik eerdaags tijd om het weer op te pakken.
Dan zal ik ook je tips meenemen!

Bedankt voor de info!

gesloten = prima

Met vriendelijke groeten,

Erik van Dalen
CAD-tekenaar
010-2582375

[image: http://www.arnicon.nl/] <http://www.arnicon.nl/>

Op 23 november 2017 om 13:07 schreef Richard Duivenvoorde <
notifications@github.com>:
