### ISSUE TITLE
tonen geometrie van locatieserver (ipv centroide)

### ISSUE THREAD

**Issue by arbakker** [rduivenvoorde/pdokservicesplugin#62]
Het is mogelijk een laag toe te voegen aan qgis die niet in het layer panel getoond wordt; zie https://gis.stackexchange.com/a/230804. 

Hiermee is het dus mogelijk de daadwerkelijk geometrie uit de locatieserver te tonen ipv alleen de centroide.

**Comment by arbakker** [comment]
Geïmplementeerd met [6b677a2](https://github.com/rduivenvoorde/pdokservicesplugin/commit/6b677a275aae0f66f9a371a5fce706fe9a3b1298):

![image](https://user-images.githubusercontent.com/3216462/175699556-5b231d1d-d992-4c43-bd5f-3a3d51f0ac6b.png)

**Comment by raymondnijssen** [comment]
Mooi! <3

**Comment by rduivenvoorde** [comment]
Nice!
Ik denk dat  deze daar mee te maken heeft:
https://github.com/rduivenvoorde/pdokservicesplugin/issues/72
maak je voor die geometry laag een aparte laag aan?
