### ISSUE TITLE
GetCapabilities van WMTS-layers worden als WMS-service aangeroepen.

### ISSUE THREAD

**Issue by wvdbee** [rduivenvoorde/pdokservicesplugin#65]
v3.7.4

De GetCapabilities van WMTS-layers worden aangeroepen met KVP _SERVICE=WMS_ terwijl het een WMTS is. Dit levert voor enkele layers een foutmelding op in het F12-scherm. Layer verschijnt met waarschuwingsicoon voor verkeerde source in het layers panel.

URL's staan wel juist geregistreerd in de pdok.json. Services plugin gaat bij deze URL's zelfstandig de SERVICE-KVP aanpassen.
![afbeelding](https://user-images.githubusercontent.com/7975556/173578354-2da7c341-e4f6-488c-adcd-6634e10e5898.png)

Layers die tot fouten leiden zijn de BGT-WMTS-layers (nieuwe URL's), TOP10NL en bag.
![afbeelding](https://user-images.githubusercontent.com/7975556/173579607-1d1bf2eb-e340-47b8-b90f-730148bbc789.png)

Layers die niet tot problemen leiden: 

- De LUFO-layers. Echter, omdat de LUFO ook als WMS wordt geserveerd én de naamgeving bij WMS en WMTS gelijk zijn, levert dat geen fout op.. De LUFO-layer wordt vervolgen met een GetTile-requests opgevraagd.
- De WMTS-services onder https://geodata.nationaalgeoregister.nl/tiles/service/wmts?  Deze service vindt het geen probleem wanneer je de GetCapabilities opvraagt met een SERVICE=WMS.

**Comment by wvdbee** [comment]
![afbeelding](https://user-images.githubusercontent.com/7975556/174856890-ca7379fa-da6f-4cb8-98f9-a23452e02dd4.png)

Gokje: regel 423 in pdokservicesplugin.py
Dataprovider staat op WMS. Moet dat geen WMTS zijn?

**Comment by rduivenvoorde** [comment]
Mmm, waarschijnlijk heb je gelijk :-)
We zijn nu met een flinke refactoring bezig, maar ik zal proberen dit tzt mee te nemen.
Dank voor de melding!

**Comment by arbakker** [comment]
Ha, ik ben hier een maand geleden al eens in gedoken en toen tot de conclusie gekomen dat dit wel de manier is om een wmts laag toe te voegen; zie bijvoorbeeld https://gis.stackexchange.com/a/230585/39741 en deze [blogpost](https://qgis.nl/2012/10/15/english-python-one-liners-for-adding-wms-wmts-wfs-layers/?lang=en) van @rduivenvoorde  (de meest autoritaire bron die ik kon vinden). 

Een werkende workaround heb ik al gevonden door query params te quoten van de wmts url; zie de code [hier](https://github.com/rduivenvoorde/pdokservicesplugin/blob/351b0f04efa2ffe362190c3816077717cdce7a55/pdokservicesplugin/pdokservicesplugin.py#L446). Deze fix zal met de nieuwe release van de plugin worden meegenomen.
