### ISSUE TITLE
URL BAG-layers not correct

### ISSUE THREAD

**Issue by FrieseWoudloper** [rduivenvoorde/pdokservicesplugin#7]
Hi,
Recently the BAG-viewer endpoint was closed down: [https://www.pdok.nl/nl/actueel/nieuws/artikel/08jul16-uitfasering-endpoint-bagviewer](https://www.pdok.nl/nl/actueel/nieuws/artikel/08jul16-uitfasering-endpoint-bagviewer)
The PDOK services plugin still references the old BAG-service that does not exist anymore, e.g. layer name Pand references [https://geodata.nationaalgeoregister.nl/bagviewer/wfs?request=getcapabilities](https://geodata.nationaalgeoregister.nl/bagviewer/wfs?request=getcapabilities). The URL should be:
https://geodata.nationaalgeoregister.nl/bag/wfs?request=getcapabilities.

Willy Bakker

**Comment by keesj** [comment]
I think it would be nice to write a test script to test the different services offered. Currently is is really a gamble if things work or not

**Comment by rduivenvoorde** [comment]
@FrieseWoudloper @keesj I do update the pdok.json file every once and a while, but I do not have an automated way of doing it. The 'test' is to run pdok2json.py (in the qgis3 branch of the plugin) which holds all url's from the 'pdok services pages'. 
Closing this one as the url's was fixed some time ago.
