### ISSUE TITLE
Runtime errro

### ISSUE THREAD

**Issue by rduivenvoorde** [rduivenvoorde/pdokservicesplugin#72]
Ik kreeg onderstaande fout toen ik in 1 sessie (zonder plugin te herladen) een 2 project laadde:

![gnome-shell-screenshot-9936bk](https://user-images.githubusercontent.com/731673/175906912-824b49d9-3b1b-4a31-98ab-fae3fb60fd17.png)

Ik ken de fout wel: de plugin denkt nog een pointer te hebben naar een (cpp) layer, maar QGIS heeft intussen die laag weggemikt...

Dit is (vind ik lastig) goed te fixen, ik zal even zoeken maar ik heb eens gevonden hoe je kon checken of de laag er ook daadwerkelijk was (in de cpp wereld), ipv alleen `is None` te gebruiken
Andere fix zou zijn om bij het herladen van een project dit soort variabelen te resetten

**Comment by arbakker** [comment]
Ha, ik heb hier een eerste aanzet voor een fix: https://github.com/rduivenvoorde/pdokservicesplugin/commit/4ecd7152bfd19b3625de444b9e421478cde1a87b 

Wat min of meer doet wat je hier boven beschrijft. Extra uitdaging erbij is dat de "hidden" ls search laag niet in het project van de gebruiker terecht moet komen. Dat is met deze commit het geval, verder werkt het in de volgende situaties:

- op save van open project 
- op opnieuw openen van huidige open project, op zowel save changes als discard changes
- op openen van andere project, op zowel save changes als discard changes

Ik luister nu zowel op cleared, readProject als writeProject event, en dat lijkt te werken, maar is miss wat overdadig, dus de oplossing moet nog even worden teruggesnoeid.

**Comment by arbakker** [comment]
Heb het probleem opgelost (zie deze branch https://github.com/rduivenvoorde/pdokservicesplugin/tree/fix-clear-ls-search-layer) , maar er zit nog een wat onfortuinlijke bug in die ik er niet uit krijg.

Als je een dmv ls search een geometrie zichtbaar is in je project en je slaat het project op, sluit het project en je opent het project weer, dan is er nog een fantoom laag  (met naam `559ba896-6a17-41ac-85e7-3dbd44e33a65` ) zichtbaar die gebruikt is voor het weergeven van de locatieserver zoek resultaten. 

Oorzaak van het probleem is denk ik dat er geen beforeProjectSaved event is om op te luisteren, enkel het [projectSaved](https://qgis.org/pyqgis/3.4/core/QgsProject.html#qgis.core.QgsProject.projectSaved) event. Ik probeer [hier](https://github.com/rduivenvoorde/pdokservicesplugin/blob/78eeaf478701b977b17a9f51a449acf6fa69c63f/pdokservicesplugin/pdokservicesplugin.py#L128) wel na het opslaan en sluiten van het project de laag te verwijderen en dan opnieuw op te slaan, maar dit lijkt niet werken - wellicht dat het project na het sluiten niet meer in scope is dus de laag niet meer verwijderd kan worden.

Ik zie zo snel geen oplossing voor het probleem, dus de vraag is of we deze feature erin moeten laten zitten in de ze vorm. Mijn voorstel zou zijn om de feature van het tonen van de ls search geoms te verwijderen en op de qgis developers mailing list een vraag te stellen hierover.  

![image](https://user-images.githubusercontent.com/3216462/176787788-31e32e02-4ba9-4329-bac3-7c71ff62cc68.png)

**Comment by rduivenvoorde** [comment]
Dank @arbakker OF we moeten toch weer terug naar wat het was, namelijk een graphic tekenen op het canvas.
OF 
Er is sinds versie 3.? ook zoiets als annotations... @raymondnijssen heb jij daar ervaring mee? 
En er is ook nog zoiets als die 'rubberband' die je kunt gebruiken daarvoor?
Ik zit me opeens af te vragen wat ze doen bij de goto-locator in QGIS zelf, die laat een punt even flitsen... misschien kunnen we ook een geom ergens laten flitsen?

Maar eens dat dit niet kan worden gereleased.... 
Ik zal dit weekend ook ff kijken nog.

**Comment by arbakker** [comment]
Een oplossing zou ook het gebruik van een scratch/memory layer kunnen zijn, die persisteren niet in een project, zie https://qgis.github.io/pyqgis/3.6/core/QgsVectorLayer.html. De docs zeggen ook over memory lagen:

> Since QGIS 3.4 when closing a project, the application shows a warning about potential data loss if there are any non-empty memory layers present. If your memory layer should not trigger such warning, it is possible to suppress that by setting the following custom variable:
> `layer.setCustomProperty(“skipMemoryLayersCheck”, 1)` 


Echter het vervangen van `virtual` door `memory` werkt niet bij het aanmaken van de laag, zie https://github.com/rduivenvoorde/pdokservicesplugin/blob/78eeaf478701b977b17a9f51a449acf6fa69c63f/pdokservicesplugin/pdokservicesplugin.py#L968 . Ik vermoed dat het op een andere manier toevoegen van de WKT geometrien aan de laag dit miss werkend kan krijgen. Ik heb zelf dit weekend geen tijd om er in te duiken, dus voel je vrij om dit te proberen.

**Comment by arbakker** [comment]
Ha, ik heb in deze commit een oplossing op basis van een memory layer, wat goed lijkt te werken:
https://github.com/rduivenvoorde/pdokservicesplugin/commit/8d10dc5eaab43f9a26ab57409cfa77c110f9afb4
@rduivenvoorde  kan jij eea nog verder testen?

**Comment by arbakker** [comment]
fixed with https://github.com/rduivenvoorde/pdokservicesplugin/pull/75
