### ISSUE TITLE
in layer_equals_fav_layer KeyError: 'service_md_id'

### ISSUE THREAD

**Issue by rduivenvoorde** [rduivenvoorde/pdokservicesplugin#77]
Foutmelding bij een daarnet geinstalleerde pdokservicesplugin in een ander dan default profile:

![gnome-shell-screenshot-jtp6s](https://user-images.githubusercontent.com/731673/179244273-c1b1ed1f-14b1-4163-852b-e72bfaf90285.png)

ik moet nog kijken of ik dit kan reproduceren...

**Comment by wvdbee** [comment]
Zelfde foutmelding. Treedt op wanneer je binnen tabblad PDOK-services een zoekopdracht doet. Ik zie nog niet meteen een relatie tussen zoekopdracht en foutmelding.

**Comment by rduivenvoorde** [comment]
Ok, ik heb even gechecked, en het heeft te maken met het feit dat inhoud van de 'keys' die in de favs in de settings zitten blijkbaar zijn veranderd (@arbakker).

De inhoud van opentopo in de oude (heeft GEEN "service_md_id" )
```
QSettings().value(f"/pdokservicesplugin/favourite_1", None)
{'abstract': None, 
'imgformats': 'image/jpeg,image/png', 
'layers': 'opentopo', 
'md_id': 'dba64422-86a0-4fc4-b23a-2ae8311b01fa', 
'name': 'opentopo', 
'servicetitle': 'Web Map Tile Service', 
'tilematrixsets': 'EPSG:28992', 
'title': 'opentopo', 
'type': 'wmts', 
'url': 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?request=GetCapabilities&service=WMTS'}
```
en de inhoud in de andere:
```
QSettings().value(f"/pdokservicesplugin/favourite_2", None)
{'abstract': '', 
'dataset_md_id': '', 
'imgformats': 'image/jpeg,image/png',
 'name': 'opentopo', 
'service_abstract': '', 
'service_md_id': 'dba64422-86a0-4fc4-b23a-2ae8311b01fa', 
'service_title': 'Web Map Tile Service', 
'service_type': 'wmts', 
'service_url': 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts?request=GetCapabilities&service=WMTS', 
'tilematrixsets': 'EPSG:28992', 
'title': 'opentopo'}
```
Dus iemand die favs had van de vorige versie, upgrade en de plugin laadt krijgt deze exceptie.

Ik moet ff bedenken hoe ik dit kan voorkomen...

**Comment by rduivenvoorde** [comment]
Going to fix this by a local fix for the key, but this will NOT fix the fact that users can have 'old' layers (or layer keys) in their setttings. But at least it will remove the Exceptions

**Comment by arbakker** [comment]
@rduivenvoorde is het geen optie om bij het initialiseren van de plugin de favorieten te upgraden? Ik had al wel een poging gedaan de favorieten te upgraden, maar kennelijk gebeurt dat te laat: https://github.com/rduivenvoorde/pdokservicesplugin/blob/90d1ccc3a5907d70edc8fe8296f75a61d9729637/pdokservicesplugin/pdokservicesplugin.py#L1182
