### ISSUE TITLE
Verouderde BGT-URL's uit de serviceslijst verwijderen

### ISSUE THREAD

**Issue by wvdbee** [rduivenvoorde/pdokservicesplugin#78]
Lijst services bevat naast de nieuwe ook nog de oude BGT-WMTS-URL's.
[Per 15-07-2022 zijn de oude BGT-URL's uitgezet. ](https://www.pdok.nl/-/oude-url-s-bgt-per-vandaag-uitgezet)
Deze oude service-URL's kunnen eruit.

![afbeelding](https://user-images.githubusercontent.com/7975556/179401880-ad223ccf-d971-473a-a388-a48910686658.png)

**Comment by rduivenvoorde** [comment]
Argh, wat een slechte plannig van pdok ;-)
Watn ik heb juist met de release een nieuwe layers.json gemaakt (en die doet dat tegenwoordig netjes op basis van het Nationaal Georegister....) Maar hier was ik blijkbaar net een dagje te vroeg.
Ik denk dat ik het even zo laat, er wordt tegenwoordig best veel van uri's gewisseld... 
Na de vakanties een nieuwe versie?
