### ISSUE TITLE
AHN WCS werken niet, en hebben allemaal een 'lege' laagnaam

### ISSUE THREAD

**Issue by rduivenvoorde** [rduivenvoorde/pdokservicesplugin#80]
Zie screenshot, als je zoekt op 'ahn' krijg je onderstaande:

Je kunt niet zien welke laag wat is:

![gnome-shell-screenshot-5blvjv](https://user-images.githubusercontent.com/731673/180183369-bb318fc4-ab86-4b63-8147-889901469714.png)

Daarnaast werkt het laden van de WCS als dataniet

**Comment by rduivenvoorde** [comment]
@raymondnijssen @arbakker @jvdkwast ik heb 't een beetje hacky gefixed. Het valt me ook op dat die WCS service SUPER sloom is... ik vraag me af of we de WCS service (die er alleen is voor AHN3) er wel in moeten houden.
Voor een HEEL klein stukje gebied, is het nog te doen, maar als je wat grotere stukken wilt, dan moet je wel erg lang wachten...

Wat vinden jullie?

**Comment by jvdkwast** [comment]
@rduivenvoorde Bedankt voor de fix! Het werkt goed. Ik zou de WCS service erin houden. Het is toch wel handig om AHN rasters op deze manier in QGIS te krijgen.

**Comment by arbakker** [comment]
We zijn nu bezig met de AHN3 services te migreren naar de nieuwe PDOK cloud infra, deze staat al onofficeel [live](https://service.pdok.nl/rws/ahn3/wcs/v1_0?service=wcs&request=getcapabilities&version=1.1.0) en is een stuk sneller dan de oude versie. Daarbij heb ik ook de metadata in de service capabilities verbetert, wat het probleem van de lege laagnamen op de juiste manier gaat fixen.

**Comment by rduivenvoorde** [comment]
@arbakker dan moeten we misschien een deel van mijn 'fix' terugdraaien:
zie https://github.com/rduivenvoorde/pdokservicesplugin/commit/237d6c99ba87bfdb575d0353b240bf6c2c6e94b9
ik zet nu in elk veld de 'id' om tenminste toch maar wat zichtbaar te hebben.

Als we het helemaal mooi willen doen moeten/kunnen we de spider netjes DescribeCoverage aanroepen laten doen...

**Comment by arbakker** [comment]
Gefixt met dit PR: https://github.com/rduivenvoorde/pdokservicesplugin/pull/85
