### ISSUE TITLE
AHN3 WCS Tool algorithm gaat fout wanneer je het vinkje 

### ISSUE THREAD

**Issue by rduivenvoorde** [rduivenvoorde/pdokservicesplugin#84]
Wanneer je van je puntenlaagje een aantal punten selecteerd, kun je een vinkje 'Selected features only' aanklikken.
De bedoeling is dan dat ipv de hele input layer, alleen de geselecteerde features worden gebruikt.

Wanneer ik dit doe, gebeurt er niets en krijg je een 'Execution failed'

![gnome-shell-screenshot-80zr8a](https://user-images.githubusercontent.com/731673/183937764-6b8cfdd9-9f0a-4981-93ff-566a5b6b992a.png)

![gnome-shell-screenshot-23yda1](https://user-images.githubusercontent.com/731673/183937658-56b19c82-6132-4a76-9953-0f8705ee9efb.png)

**Comment by arbakker** [comment]
Opgelost met https://github.com/rduivenvoorde/pdokservicesplugin/commit/e81abdf69cd3cad10596f259eeadb83027545d49
