### ISSUE TITLE
pdok in Qgis overschrijdt de hoogte van het beeldscherm

### ISSUE THREAD

**Issue by gisomgeving** [rduivenvoorde/pdokservicesplugin#86]
Bij gebruik van Qgis in een vnc omgeving overschrijdt de PDOK service plugin de hoogte van het beeldscherm, waardoor bij een selectie de buttons niet gebrikt kunnen worden.
Hoe is dit op te lossen?

**Comment by rduivenvoorde** [comment]
Wat is de hoogte (in pixels) van je scherm?
Want de grootte van de dialoog bepalen wij bij het maken van de ui-file in QDesigner.
Die kan evt wel wat kleiner (of althans, we kunnen de 'minimal height' waarschijnljk wel kleiner maken.
Maar dan moeten we even een indicatie van de gewenste hoogte hebben.
Een screendumpje helpt ook.

Vaak kun je trouwens met de 'windows'-knop ingedrukt, met de muis op een willekeurige plek in de dialoog, de hele dialoog verschuiven (dus ipv met het balkje boven)

**Comment by arbakker** [comment]
Issue gesloten wegens gebrek aan reactie.
