### ISSUE TITLE
Verbeterde URL voor NWB

### ISSUE THREAD

**Issue by Bussink** [rduivenvoorde/pdokservicesplugin#89]
De service NWB wegen - wegvakken gebruikt nu deze url : https://geodata.nationaalgeoregister.nl/nwbwegen/wfs?request=GetCapabilities&service=WFS
nwbwegen:wegvakken
 
De gemeentelijke wegen zijn grijs gekleurd en vallen tegen veel achtergrond kaarten weg. <BR><BR>De PDOK viewer gebruikt deze https://service.pdok.nl/rws/nwbwegen/wms/v1_0?VERSION=1.3.0 waar gemeentelijke wegen blauw zijn gekleurd.
![image](https://user-images.githubusercontent.com/40763787/201193000-3a8b6232-e1f9-4353-9950-4d70991ddd18.png)

Is het een idee om de url aan te passen in de PDOKserviceplugin?

**Comment by Bussink** [comment]
deze file https://raw.githubusercontent.com/rduivenvoorde/pdokservicesplugin/master/pdokservicesplugin/resources/layers-pdok.json <BR>

In deze code:<BR>
```
 {
    "name": "wegvakken",
    "title": "wegvakken",
    "abstract": "",
    "styles": [
      {
        "name": "wegvakken",
        "title": "wegvakken"
      }
    ],
    "crs": "EPSG:28992",
    "minscale": "",
    "maxscale": "50000",
    "dataset_md_id": "a9b7026e-0a81-4813-93bd-ba49e6f28502",
    "imgformats": "image/png,image/jpeg,image/png; mode=8bit,application/x-pdf,image/svg+xml,image/tiff,application/vnd.google-earth.kml+xml,application/vnd.google-earth.kmz",
    "service_url": "https://geodata.nationaalgeoregister.nl/nwbwegen/wms?request=GetCapabilities&service=WMS",
    "service_title": "NWB wegen",
    "service_type": "wms",
    "service_abstract": "NWB wegen",
    "service_md_id": "f2437a92-ddd3-4777-a1bc-fdf4b4a7fcb8"
  },
```

**Comment by arbakker** [comment]
Opgelost met update van de layer config: https://github.com/rduivenvoorde/pdokservicesplugin/commit/18105da366f94bf5f284d82e1a4dae584cb0d00c

Update van de plugin komt binnenkort!
