### ISSUE TITLE
Fout in URL Top10NL en BGT

### ISSUE THREAD

**Issue by johnyhas61** [rduivenvoorde/pdokservicesplugin#90]
Als via de plugin de Top10NL of de BGT achtergrondkaarten als WMTS worden toegevoegd werken ze niet. Als je de eigenschappen van de laag opvraagt staat er in de url een dubbele / achter https://services.pdok.nl. 

![image](https://user-images.githubusercontent.com/4522642/207313103-56790b41-2c6b-4539-ad41-8698fe58b142.png)

**Comment by raymondnijssen** [comment]
En als je die aanpast werkt het wel? Want bij mij werkt het wel met // (in QGIS 3.29)
![image](https://user-images.githubusercontent.com/681851/207314614-13000d16-9f96-41b3-a2fa-b4764781e901.png)

**Comment by johnyhas61** [comment]
> En als je die aanpast werkt het wel? Want bij mij werkt het wel met // (in QGIS 3.29) ![image](https://user-images.githubusercontent.com/681851/207314614-13000d16-9f96-41b3-a2fa-b4764781e901.png)

De BRT werkt bij mij ook, maar de Top10NL en BGT lagen niet. Kennelijk ligt het dan toch niet aan die dubbele //

**Comment by johnyhas61** [comment]
> > En als je die aanpast werkt het wel? Want bij mij werkt het wel met // (in QGIS 3.29) ![image](https://user-images.githubusercontent.com/681851/207314614-13000d16-9f96-41b3-a2fa-b4764781e901.png)
> 
> De BRT werkt bij mij ook, maar de Top10NL en BGT lagen niet. Kennelijk ligt het dan toch niet aan die dubbele //

De lagen doen het toch wel, maar alleen op een hele grote schaal (bij mij pas vanaf 1:4080)

**Comment by raymondnijssen** [comment]
Top 10 werkt bij mij ook gewoon. Heb je de nieuwste versie van de plugin (4.1.2)? Of kun je misschien upgraden? De PDOK endpoints veranderen nog wel eens.


![image](https://user-images.githubusercontent.com/681851/207367873-2e43d90b-e51d-4b21-b9be-d6fe90f43f9b.png)

**Comment by johnyhas61** [comment]
> Top 10 werkt bij mij ook gewoon. Heb je de nieuwste versie van de plugin (4.1.2)? Of kun je misschien upgraden? De PDOK endpoints veranderen nog wel eens.
> 
> ![image](https://user-images.githubusercontent.com/681851/207367873-2e43d90b-e51d-4b21-b9be-d6fe90f43f9b.png)

Ik heb ook plugin versie 4.1.2. Ik denk dat er dan toch iets anders aan de hand is. Ik ga eens even uitzoeken wat dat kan zijn.

![image](https://user-images.githubusercontent.com/4522642/207374277-ebdbe9ed-0249-421d-a2bd-8521ed038b63.png)

**Comment by arbakker** [comment]
Er zitten iig dubbele slashes in de [`layers-pdok.json`](https://raw.githubusercontent.com/rduivenvoorde/pdokservicesplugin/453cd3ca0dab3f2f35a75c2b03399d5933932da8/pdokservicesplugin/resources/layers-pdok.json). 

Geupdate in deze commit https://github.com/rduivenvoorde/pdokservicesplugin/commit/453cd3ca0dab3f2f35a75c2b03399d5933932da8 . Ik ga ervanuit dat het probleem hiermee is opgelost, en sluit dit ticket. Voel je vrij een nieuw ticket aan te maken mocht het nog voorkomen in de komende release.
