### ISSUE TITLE
Foutmelding 'Ongeldige laag' bij laden PDOK lagen QGIS 2.18

### ISSUE THREAD

**Issue by JanW2093** [rduivenvoorde/pdokservicesplugin#91]
Hallo,

Bij het gebruiken van de PDOK plugin in QGIS 2.18 krijg ik sinds vandaag de volgende foutmelding bij het laden van kaarten:
"Ongeldige Laag: WMS provider Tile-laag of Tile-matrix set niet gevonden WMS provider Kan CRS niet instellen Raster layer Provider is ongeldig (provider: wms, URI: tileMatrixSet=EPSG:28992&crs=EPSG:28992&layers=opentopo&styles=default&format=image/jpeg&url=https://geodata.nationaalgeoregister.nl/wmts?VERSION%3D1.0.0%26request%3DGetCapabilities)"

Dit gebeurt in zowel bestaande als nieuwe projecten. 
Kan iemand mij hiermee helpen?

**Comment by raymondnijssen** [comment]
QGIS 2.18 is al jaren oud. Heb je de mogelijkheid om te upgraden naar een nieuwe versie van QGIS, bijvoorbeeld 3.22 of 3.28? De huidige plugin updates werken alleen vanaf QGIS 3.10.
