### ISSUE TITLE
"Opentopo" niet meer beschikbaar

### ISSUE THREAD

**Issue by bvdbos** [rduivenvoorde/pdokservicesplugin#92]
De laag "Opentopo" is niet meer beschikbaar, het bedrijf wat deze maakte is overgestapt naar een betaalde dienst... Bij het laden van de laag met de plugin krijg je een foutmelding:
![afbeelding](https://user-images.githubusercontent.com/1064079/210335099-21814366-f621-4711-8066-33702bed6330.png)
meer info:
https://www.spotinfo.nl/wp/topoplus/

Mogelijk hetzelfde issue als in https://github.com/rduivenvoorde/pdokservicesplugin/issues/91 ?

**Comment by raymondnijssen** [comment]
Klopt, deze lagen worden sinds 1 januari 2023 niet meer gehost door PDOK en zullen na de volgende update van de plugin niet meer worden getoond. Is niet gerelateerd aan #91

**Comment by rduivenvoorde** [comment]
En in aanvulling daarop: ik vind het echt superjammer dat PDOK niet een alternatief heeft.
Ik hoop dat ze nog wel iets gaan bieden

Ik denk, afhankelijk van je gebruik/geld dat je OF een contract af kan sluiten bij een van de clubs die (gesloten)opentopo nog wel aanbieden, of je OpenStreetMap (als xyz laag) kan gebruiken.

**Comment by JanW2093** [comment]
> De laag "Opentopo" is niet meer beschikbaar, het bedrijf wat deze maakte is overgestapt naar een betaalde dienst... Bij het laden van de laag met de plugin krijg je een foutmelding: ![afbeelding](https://user-images.githubusercontent.com/1064079/210335099-21814366-f621-4711-8066-33702bed6330.png) meer info: https://www.spotinfo.nl/wp/topoplus/
> 
> Mogelijk hetzelfde issue als in #91 ?

Bedankt, ik denk dat dit inderdaad ook mijn probleem was. Als ik het goed begrijp is er dus geen alternatief als achtergrondkaart in PDOK op dit moment?
Als iemand daar een oplossing voor heeft, hoor ik het graag!

**Comment by bvdbos** [comment]
De Quickmapservices plugin, dan even naar instellingen gaan en de andere kaarten ook toevoegen. Dan krijg je OSM er bij, Of de BGT-import. Maar die zijn niet zo goed als opentopo in mijn optiek...

**Comment by raymondnijssen** [comment]
Hij zit ook gewoon onder XYZ-tiles in je Browser panel:
![image](https://user-images.githubusercontent.com/681851/210349849-b5ee3b20-e075-4fab-b1a2-ab24cd19ec35.png)

**Comment by arbakker** [comment]
Ik sluit het ticket, gezien buiten scope van de broncode van de plugin.
