### ISSUE TITLE
blijvende marker bij adreszoeker

### ISSUE THREAD

**Issue by Michiel-werk** [rduivenvoorde/pdokservicesplugin#95]
Beste, 

Sinds begin deze week lijkt er iets gewijzigd in het zoeken van een locatie. Bij het intypen van een adres worden er suggesties gegeven. Het is nu alleen mogelijk om naar een locatie te gaan door één van deze suggesties te selecteren. Helemaal prima. 
Voorheen werd de locatie aangemerkt met een gele marker (kruisje) die bleef staan, op dit moment is dit een rode contour die snel vervaagd. Ik heb de wens dat er een blijvende marker blijft staan (zoals voorheen). Is er een optie om zo'n marker permanent te maken? 

Nu zie ik geen update van de plugin (laatste update van sep 2022), is er wellicht toch iets gewijzigd of heeft het te maken met een koppeling met extern (waarschijnlijk BAG)? 

Ik gebruik qgis 3.16 op windows 10.  

alvast bedankt.

**Comment by rduivenvoorde** [comment]
Hi Michiel, probeer eens de nieuwe versie. Ik heb het gele kruisje weer tevoorschijn getoverd! \o/
