### ISSUE TITLE
PDOK AHN3 WCS Tool - WCS-service URL onjuist

### ISSUE THREAD

**Issue by pewako** [rduivenvoorde/pdokservicesplugin#97]
De PDOK AHN3 WCS Tool functioneert niet meer. Eerder dit jaar is de service-url gewijzigd van:
https://geodata.nationaalgeoregister.nl/ahn3/wcs
naar:
https://service.pdok.nl/rws/ahn3/wcs/v1_0

**Comment by arbakker** [comment]
Fixed with:

- https://github.com/rduivenvoorde/pdokservicesplugin/commit/ff5bf629c51acf48ab54744e468b5a20cd0c11f2
- https://github.com/rduivenvoorde/pdokservicesplugin/commit/1fb246b991ef49c773003320adb804b2837ee344
