### ISSUE TITLE
wfs cbs 2021 buurten en wijken verkeerde verwijzing

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [rduivenvoorde/pdokservicesplugin#98]
Hoi,

de verwijzingen naar de kaartlagen CBS Wijken en Buurten 2021 versie 1 WFS doen het niet. Dit geldt voor gemeenten, wijken en voor buurten.
In PDOK zijn deze vervangen door versie 2
https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/60dc9632-50c8-40b1-ac63-cd91b85352d2

de serie van 2020 verwijst wel goed naar versie 2, die werken dus prima.

En, mag de serie 2022 ook al worden toegevoegd? Dat is nog versie 1, want de update naar versie 2 komt pas in het najaar.
https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/70c52fd8-6b2e-42aa-873a-742711903243

**Comment by arbakker** [comment]
Opgelost met https://github.com/rduivenvoorde/pdokservicesplugin/commit/18105da366f94bf5f284d82e1a4dae584cb0d00c,  nieuwe release komt binnenkort!
