### ISSUE TITLE
Het is niet mogelijk om OpenTopo shortcut (meer) te verwijderen

### ISSUE THREAD

**Issue by rduivenvoorde** [rduivenvoorde/pdokservicesplugin#99]
Wanneer je een favoriet hebt naar OpenTopo, met een nwe versie van de plugin (die de service niet meer bevat), dan kun je 'm NIET meer verwijderen.
Want we doen dat door in de laag-eigenschappen op het (dan) gele sterretje te klikken..
Maar de laag eigenschappen van opentopo zijn er niet meer...

**Comment by LuukS** [comment]
Dit geld voor alle oude favorieten. Ik heb een oude favoriet naar de 'Standaard' BRT Achtergrondkaart waarvan ik de volgende melding krijg als ik deze wil toevoegen:
Geen favoriet aanwezig (of verouderd)
Maak een favoriet aan door in de dialoog met services en lagen via het context menu (rechter muisknop) een Favoriet te kiezen...

Ik zou graag de vraag willen krijgen of deze niet werkende favoriet verwijderd moet worden.

**Comment by rduivenvoorde** [comment]
@raymondnijssen @arbakker net weer een mail ontvangen hierover, iemand een idee voor een snelle fix?

**Comment by raymondnijssen** [comment]
Misschien alle niet-bestaande favorieten verwijderen bij opstarten van de plugin?

**Comment by rduivenvoorde** [comment]
Ja, goed idee! Zal evne kijken of dat makkelijk is te doen

**Comment by rduivenvoorde** [comment]
Fixed in 0.4.2: wanneer je een niet werkende shortcut hebt, wordt gevraagd of je 'm wilt verwijderen.
